### ISSUE TITLE
Feature Request: Automate Video AG Login

### ISSUE THREAD

**Issue by vincentscode** [Rc-Cookie/quality-of-rwth#1]
## Motivation
Hi, this extension is great in automating some of the logins, but it does not automatically login for RWTH Video.

## Required Steps
1. Recognize that Login is required (e.g. https://rwth.video/19ss-lainf/14125)
![image](https://github.com/Rc-Cookie/quality-of-rwth/assets/26576880/ee6954eb-4b99-40af-a698-8c811ce6ec59)
2. Open https://rwth.video/internal/rwthauth
3. Automatically select RWTH at https://oauth.campus.rwth-aachen.de/login/shibboleth/?q=verify&d=...
![image](https://github.com/Rc-Cookie/quality-of-rwth/assets/26576880/eef2daa1-e62a-45a2-a052-5d9a4d0da1f1)
4. Automatically Authorize "Video AG" at https://oauth.campus.rwth-aachen.de/manage/?q=verify&d=... (Submits a hidden form)
![image](https://github.com/Rc-Cookie/quality-of-rwth/assets/26576880/45907b10-b30b-4459-80f2-4b8de9061174)
5. Automatically close the OAuth page as it is no longer required and return to rwth.video (reload it to update login state)

**Comment by Rc-Cookie** [comment]
Already working on that, not sure whether I will auto-authorize though because some people may have security concerns with that. Maybe I'll add an option for that in the settings which is disabled by default.

**Comment by vincentscode** [comment]
Yeah, I do agree with the security concerns.
The main annoyance here is that RWTH Video asks for those permissions every time and not just once.
So maybe you could save if permission was given before and only automatically authorize if that is the case.

**Comment by Rc-Cookie** [comment]
I can try implementing that

**Comment by Rc-Cookie** [comment]
It is more difficult though, because I don't see any way to identify the requesting application, other than by name. Good enough, I guess

**Comment by vincentscode** [comment]
Yeah, the App Name should be fairly unique considering that every application has to be approved etc.

**Comment by Rc-Cookie** [comment]
Implemented in version 1.1.0
