### ISSUE TITLE
treat git-ce.rwth-aachen.de like git.rwth-aachen.de

### ISSUE THREAD

**Issue by jonsch318** [Rc-Cookie/quality-of-rwth#11]
**Explain the feature**
When using git.rwth-aachen.de the landing/login page is automatically skipped.
This should happen for git-ce.rwth-aachen.de aswell. 
Should be simple thus no pull request needed.

**Which browser are you using?**
doesnt matter

**Comment by Rc-Cookie** [comment]
Implemented in version 1.8.13
