### ISSUE TITLE
Feature Request: Open Course in new tab (Right/Middle Click)

### ISSUE THREAD

**Issue by Laurenshup** [Rc-Cookie/quality-of-rwth#2]
Instead of opening a course on the current tab, add the possibility to open a course in a new tab. This would be possible by either right or middle clicking on that course.

**Comment by Rc-Cookie** [comment]
Actually already implemented for Firefox with middle mouse click, however, does not seem to work in Chrome

**Comment by Laurenshup** [comment]
A fix would be using \<a\> tags rather than \<div\> tags. Using CSS the underline can be romoved.

**Comment by Rc-Cookie** [comment]
Actually, I was using \<a\> in the first place, however, then regular clicking won't work out of the box, because the popup is threaded as the current document. In Firefox the target page gets actually loaded into the popup window, in Chrome simply nothing happens.

**Comment by Rc-Cookie** [comment]
It seems to be a bug of Chrome popups, if I open the popup page directly, the auxclick event fires as it should. I will see what I can do anyways.

**Comment by Rc-Cookie** [comment]
Resolved in version 1.1.1
