### ISSUE TITLE
Bug: Not Auto-Redirecting on rwth.video

### ISSUE THREAD

**Issue by vincentscode** [Rc-Cookie/quality-of-rwth#4]
While #1 has been implemented for `video.fsmpi.rwth-aachen.de` it does currently not work on `rwth.video`.

**Comment by Rc-Cookie** [comment]
Do you have an example page?

**Comment by Rc-Cookie** [comment]
Or rather, I don't see where you would need to log in there in the first place

**Comment by vincentscode** [comment]
https://rwth.video/19ss-lainf/14125 for example. rwth.video and video.fsmpi.rwth-aachen.de just map to the same page.

**Comment by Rc-Cookie** [comment]
Implemented in v1.3.0

**Comment by Rc-Cookie** [comment]
I didn't actually ever notice that video.fsmpi.rwth-aachen.de was not a moodle page
