### ISSUE TITLE
ChromePorter not working

### ISSUE THREAD

**Issue by jonsch318** [Rc-Cookie/quality-of-rwth#6]
Now the deps. are not the problem anymore but, when running `mvn exec:java`

The error is: `[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.1.0:java (default-cli) on project web-ext-chrome-porter: The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:3.1.0:java are missing or invalid -> [Help 1]`

**Comment by Rc-Cookie** [comment]
I personally always just run it from IntelliJ. I have however added support for `mvn exec:java` and `mvn assembly:single` to build and run it using Maven.

If you use `mvn assembly:single` Maven will build a jar (in `/target`) with all dependencies included which you can then execute using `java -jar`. You also need to specify the root directory which contains the "Firefox" and "Chrome" directory, so pass "../.." if you execute it from the target directory.

If you use `mvn exec:java` you have to pass the parameter like this: `"-Dexec.args=../.."`.

Either way, remember to first run `mvn compile`.
